# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='last_name name'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='middle name'),
        ),
    ]
