# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPost', '0002_auto_20160818_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-modified_at']},
        ),
    ]
