# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPost', '0003_auto_20160818_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='image',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='image'),
        ),
    ]
