# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 23, 19, 46, 14, 352955, tzinfo=utc), verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobbygroup',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 23, 19, 46, 35, 283667, tzinfo=utc), verbose_name='Modified at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobbygroupuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 23, 19, 46, 50, 889188, tzinfo=utc), verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobbygroupuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 23, 19, 46, 54, 279789, tzinfo=utc), verbose_name='Modified at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 23, 19, 47, 1, 156261, tzinfo=utc), verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 23, 19, 47, 4, 801801, tzinfo=utc), verbose_name='Modified at'),
            preserve_default=False,
        ),
    ]
