# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0002_auto_20160815_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(max_length=15000),
        ),
    ]
