# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0003_auto_20160816_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('modified_at',)},
        ),
    ]
