# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyapp', '0004_auto_20160818_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-modified_at',)},
        ),
    ]
